### ISSUE TITLE
incorrect context property names

### ISSUE THREAD

**Issue by ericrqs** [QualiSystems/shell-networking-standard#25]
The template contains:

from cloudshell.shell.core.resource_driver_interface import ResourceDriverInterface
from cloudshell.shell.core.driver_context import InitCommandContext
from cloudshell.shell.core.driver_context import ResourceCommandContext
from cloudshell.shell.core.driver_context import AutoLoadResource
from cloudshell.shell.core.driver_context import AutoLoadAttribute
from cloudshell.shell.core.driver_context import AutoLoadDetails
from cloudshell.shell.core.driver_context import CancellationContext

Properties I expected based on the imported classes:

context.connectivity.serverAddress                                     context.connectivity.token
context.connectivity.tsAPIPort

But for it to work correctly under 7.0, I found that you have to use:

context.connectivity.server_address
context.connectivity.admin_auth_token
context.connectivity.cloudshell_api_port

**Comment by kalsky** [comment]
you actually have to use "from cloudshell.shell.core.context" instead.
we need to fix the template.
