### ISSUE TITLE
Address of some sub-resources isn't unique in current definition

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/shell-networking-standard#4]
Currently the address in CloudShell of modules, sub-modules and ports is numeric only. This causes autoload to fail in devices in which there are modules, sub-modules or ports in the same level - since they get the same address.

Need to add letters to Module, Sub-Module and Port address in CloudShell, so their address will be in the format "M<ID>", "SM<ID>" and "P<ID>" respectively.

This change will be breaking, and upgrade will require (1) new autoload (2) recreating the physical connections if exist (3) delete excluded original modules/sub-modules/ports

**Comment by GalcQuali** [comment]
Updated in standard 5.0.0
