### ISSUE TITLE
SNMP credentials attributes should change from string to password

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/shell-networking-standard#5]
Currently the attributes "SNMP V3 Password", "SNMP Read Community" and "SNMP Write Community" are string although they contain a password. This presents a security issue for our customers.

Need to change the attributes to be of type password.

This change is breaking and upgrade will require some SQL script and/or migration step + updating the drivers

**Comment by GalcQuali** [comment]
Updated in standard 5.0.0
